version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - CONNECTION_URL=${CONNECTION_URL}
    networks:
      - mern-net

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_GOOGLE_OAUTH_CLIENT_ID: ${VITE_GOOGLE_OAUTH_CLIENT_ID}
    ports:
      - "80:80"
    environment:
      - VITE_GOOGLE_OAUTH_CLIENT_ID=${VITE_GOOGLE_OAUTH_CLIENT_ID}
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
